name: smart_kid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  provider: ^6.1.1
  cloud_firestore: ^4.15.5
  flutter_screenutil: ^5.9.0
  flutter_card_swiper: ^7.0.0
  palette_generator: ^0.3.3+3
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Linotte-Bold
      fonts:
        - asset: fonts/Linotte-Bold.otf
    - family: Linotte-Heavy
      fonts:
        - asset: fonts/Linotte-Heavy.otf
    - family: Linotte-Light
      fonts:
        - asset: fonts/Linotte-Light.otf
    - family: Linotte-Regular
      fonts:
        - asset: fonts/Linotte-Regular.otf
    - family: Linotte-SemiBold
      fonts:
        - asset: fonts/Linotte-Semibold.otf
