// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIi-WBWCYvVtb-99swarODPK_3vTVlAos',
    appId: '1:855375103538:web:60485c27c98b9c28495e2b',
    messagingSenderId: '855375103538',
    projectId: 'smart-kids-c27f9',
    authDomain: 'smart-kids-c27f9.firebaseapp.com',
    storageBucket: 'smart-kids-c27f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6NcypYpIU_PY1A5pAeBsR1jyBIsNX0Y',
    appId: '1:855375103538:android:033f017792e94f5c495e2b',
    messagingSenderId: '855375103538',
    projectId: 'smart-kids-c27f9',
    storageBucket: 'smart-kids-c27f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKdmV1lgdVgtJt1QlyQNAcwQ3TI7k_Pc',
    appId: '1:855375103538:ios:dc5e026880b44322495e2b',
    messagingSenderId: '855375103538',
    projectId: 'smart-kids-c27f9',
    storageBucket: 'smart-kids-c27f9.appspot.com',
    iosBundleId: 'org.smart.kids.smartKid',
  );
}
